import { Department, Feature, Testimonial, VideoCard } from "./types";

export const DEPARTMENTS: Department[] = [
  {
    id: "tech-edu",
    title: "تكنولوجيا التعليم",
    description: "إعداد كوادر متخصصة في تصميم وإنتاج الوسائل التعليمية الحديثة.",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=800",
    overview: "يهدف القسم إلى إعداد أخصائي تكنولوجيا تعليم قادر على التعامل مع المستحدثات التكنولوجية وتوظيفها في العملية التعليمية.",
    vision: "الريادة في مجال تكنولوجيا التعليم والتعلم الرقمي على المستوى المحلي والإقليمي.",
    mission: "تقديم برامج تعليمية وبحثية متميزة في مجال تكنولوجيا التعليم تلبي احتياجات سوق العمل.",
    duration: "4 سنوات",
    subjects: ["إنتاج الوسائل التعليمية", "تصميم البرمجيات التعليمية", "صيانة الأجهزة التعليمية", "التعليم الإلكتروني"],
    careers: ["أخصائي تكنولوجيا تعليم بالمدارس", "مصمم حقائب تعليمية", "مدرب تكنولوجي", "مطور محتوى إلكتروني"],
    headOfDept: {
      name: "أ.د. محمد أحمد",
      image: "https://avatar.iran.liara.run/public/boy?username=mohamed",
      role: "رئيس قسم تكنولوجيا التعليم",
      gender: "male",
    },
    gallery: [
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=400",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=400",
    ],
  },
  {
    id: "early-childhood",
    title: "رياض الأطفال",
    description: "تأهيل معلمات متميزات لبناء أجيال المستقبل في مرحلة الطفولة المبكرة.",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&q=80&w=800",
    overview: "يركز القسم على الجوانب النفسية والتربوية للطفل وكيفية تنمية مهاراته في سن مبكرة.",
    vision: "إعداد معلمة رياض أطفال مبدعة وقادرة على المنافسة.",
    mission: "توفير بيئة تعليمية محفزة للنمو الشامل للطفل.",
    duration: "4 سنوات",
    subjects: ["علم نفس الطفل", "أدب الأطفال", "ألعاب تعليمية", "إرشاد تربوي"],
    careers: ["معلمة رياض أطفال", "أخصائية تعديل سلوك", "مصممة ألعاب تربوية"],
    headOfDept: {
      name: "أ.د. فاطمة علي",
      image: "https://avatar.iran.liara.run/public/girl?username=fatma",
      role: "رئيس قسم رياض الأطفال",
      gender: "female",
    },
    gallery: [
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=400",
      "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?auto=format&fit=crop&q=80&w=400",
    ],
  },
  {
    id: "edu-media",
    title: "الإعلام التربوي",
    description: "دمج الفكر التربوي بالمهارات الإعلامية (صحافة، إذاعة، مسرح).",
    image: "https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&q=80&w=800",
    overview: "إعداد أخصائي إعلام تربوي ملم بفنون الصحافة والإذاعة والمسرح المدرسي.",
    vision: "التميز في إعداد الكوادر الإعلامية التربوية.",
    mission: "تطوير المهارات الإعلامية للطلاب في إطار تربوي.",
    duration: "4 سنوات",
    subjects: ["الصحافة المدرسية", "الإذاعة المدرسية", "المسرح التعليمي", "فنون الإلقاء"],
    careers: ["أخصائي إعلام تربوي", "معد برامج تعليمية", "صحفي تربوي"],
    headOfDept: {
      name: "أ.د. حسن محمود",
      image: "https://avatar.iran.liara.run/public/boy?username=hassan",
      role: "رئيس قسم الإعلام التربوي",
      gender: "male",
    },
    gallery: [
      "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&q=80&w=400",
      "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&q=80&w=400",
    ],
  },
  {
    id: "music-edu",
    title: "التربية الموسيقية",
    description: "تنمية المواهب الفنية وتدريس الموسيقى بأساليب علمية متطورة.",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&q=80&w=800",
    overview: "دراسة النظريات الموسيقية والعزف على الآلات المختلفة وتدريسها.",
    vision: "الارتقاء بالذوق الفني والموسيقي في المجتمع.",
    mission: "تخريج معلم موسيقى متمكن فنياً وتربوياً.",
    duration: "4 سنوات",
    subjects: ["صولفيج", "عزف بيانو", "تاريخ الموسيقى", "طرق تدريس الموسيقى"],
    careers: ["معلم تربية موسيقية", "عازف محترف", "مدرب كورال"],
    headOfDept: {
      name: "أ.د. منى حسن",
      image: "https://avatar.iran.liara.run/public/girl?username=mona",
      role: "رئيس قسم التربية الموسيقية",
      gender: "female",
    },
    gallery: [
      "https://images.unsplash.com/photo-1514320299924-9b0a28218293?auto=format&fit=crop&q=80&w=400",
      "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&q=80&w=400",
    ],
  },
  {
    id: "home-econ",
    title: "الاقتصاد المنزلي",
    description: "دراسة فنون الطهي، التصميم، وإدارة الموارد الأسرية.",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=800",
    overview: "تأهيل الطالبات في مجالات التغذية والملابس وإدارة المنزل.",
    vision: "التميز في مجالات الاقتصاد المنزلي المختلفة.",
    mission: "إعداد خريج قادر على تطوير جودة الحياة الأسرية.",
    duration: "4 سنوات",
    subjects: ["علوم الأغذية", "تصميم الأزياء", "إدارة المنزل", "أشغال فنية"],
    careers: ["معلمة اقتصاد منزلي", "أخصائية تغذية", "مصممة أزياء"],
    headOfDept: {
      name: "أ.د. زينب محمود",
      image: "https://avatar.iran.liara.run/public/girl?username=zeinab",
      role: "رئيس قسم الاقتصاد المنزلي",
      gender: "female",
    },
    gallery: [
      "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=400",
      "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=400",
    ],
  },
  {
    id: "computer-teacher",
    title: "برنامج معلم الحاسب",
    description: "إعداد معلم حاسب آلي متميز لمواكبة التحول الرقمي.",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800",
    overview: "دراسة لغات البرمجة، قواعد البيانات، وشبكات الحاسب.",
    vision: "الريادة في إعداد معلم الحاسب الآلي.",
    mission: "توفير تعليم تقني متميز يواكب الثورة الرقمية.",
    duration: "4 سنوات",
    subjects: ["برمجة هيكلية", "قواعد بيانات", "هندسة برمجيات", "شبكات"],
    careers: ["معلم حاسب آلي", "مبرمج", "مسئول تطوير تكنولوجي"],
    headOfDept: {
      name: "أ.د. إبراهيم علي",
      image: "https://avatar.iran.liara.run/public/boy?username=ibrahim",
      role: "رئيس برنامج معلم الحاسب",
      gender: "male",
    },
    gallery: [
      "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&q=80&w=400",
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=400",
    ],
  },
  {
    id: "speech-therapy",
    title: "اضطرابات النطق والكلام",
    description: "تخصص إنساني يهدف لعلاج مشاكل التواصل اللغوي.",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=800",
    overview: "دراسة تشريح جهاز النطق وعلاج اللثغات والتلعثم.",
    vision: "التميز في تقديم خدمات التخاطب والبحث العلمي.",
    mission: "إعداد أخصائي تخاطب متميز علمياً ومهارياً.",
    duration: "4 سنوات",
    subjects: ["تشريح جهاز النطق", "علاج اضطرابات اللغة", "تخاطب", "علم نفس لغوي"],
    careers: ["أخصائي تخاطب", "باحث في علوم اللغة", "مدرب تواصل"],
    headOfDept: {
      name: "أ.د. كمال حسن",
      image: "https://avatar.iran.liara.run/public/boy?username=kamal",
      role: "رئيس قسم اضطرابات النطق",
      gender: "male",
    },
    gallery: [
      "https://images.unsplash.com/photo-1573497491208-6b1acb260507?auto=format&fit=crop&q=80&w=400",
      "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=400",
    ],
  },
  {
    id: "theater-edu",
    title: "التربية المسرحية",
    description: "استخدام المسرح كأداة تربوية فعالة لتنمية الشخصية.",
    image: "https://images.unsplash.com/photo-1503095396549-807a8bc3667c?auto=format&fit=crop&q=80&w=800",
    overview: "دراسة فنون التمثيل والإخراج والديكور المسرحي.",
    vision: "تفعيل دور المسرح في العملية التربوية.",
    mission: "تخريج كوادر مسرحية تربوية مبدعة.",
    duration: "4 سنوات",
    subjects: ["تمثيل وإخراج", "ديكور مسرحي", "تاريخ المسرح", "نقد مسرحي"],
    careers: ["أخصائي مسرح مدرسي", "مخرج مسرحي", "ممثل"],
    headOfDept: {
      name: "أ.د. عادل محمود",
      image: "https://avatar.iran.liara.run/public/boy?username=adel",
      role: "رئيس قسم التربية المسرحية",
      gender: "male",
    },
    gallery: [
      "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&q=80&w=400",
      "https://images.unsplash.com/photo-1503095396549-807a8bc3667c?auto=format&fit=crop&q=80&w=400",
    ],
  },
  {
    id: "art-edu",
    title: "التربية الفنية",
    description: "إطلاق العنان للإبداع من خلال الرسم والنحت والأشغال اليدوية.",
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&q=80&w=800",
    overview: "دراسة الفنون التشكيلية وتاريخ الفن وطرق التعبير الفني.",
    vision: "الريادة في الفنون التشكيلية والتربية الفنية.",
    mission: "إعداد فنان معلم قادر على تنمية الحس الجمالي.",
    duration: "4 سنوات",
    subjects: ["رسم وتصوير", "نحت وخزف", "تاريخ فن", "أشغال معادن"],
    careers: ["معلم تربية فنية", "فنان تشكيلي", "مصمم جرافيك"],
    headOfDept: {
      name: "أ.د. هاني علي",
      image: "https://avatar.iran.liara.run/public/boy?username=hany",
      role: "رئيس قسم التربية الفنية",
      gender: "male",
    },
    gallery: [
      "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&q=80&w=400",
      "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=400",
    ],
  },
  {
    id: "edu-sciences",
    title: "العلوم التربوية",
    description: "الأساس النظري والعملي لمهنة التعليم والبحث التربوي.",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=800",
    overview: "دراسة أصول التربية وعلم النفس التربوي والمناهج.",
    vision: "التميز في البحث التربوي وإعداد المعلم.",
    mission: "تطوير الفكر التربوي وتطبيقاته في الميدان التعليمي.",
    duration: "4 سنوات",
    subjects: ["أصول التربية", "علم النفس التربوي", "تكنولوجيا التعليم", "مناهج"],
    careers: ["باحث تربوي", "مخطط مناهج", "مستشار تعليمي"],
    headOfDept: {
      name: "أ.د. سعيد محمود",
      image: "https://avatar.iran.liara.run/public/boy?username=said",
      role: "رئيس قسم العلوم التربوية",
      gender: "male",
    },
    gallery: [
      "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=400",
      "https://images.unsplash.com/photo-1454165833767-027ffea9e77b?auto=format&fit=crop&q=80&w=400",
    ],
  },
];

export const FEATURES: Feature[] = [
  {
    id: 1,
    title: "تدريب عملي",
    description: "معامل مجهزة بأحدث التقنيات لضمان اكتساب المهارات العملية.",
    icon: "GraduationCap",
  },
  {
    id: 2,
    title: "أعضاء هيئة تدريس",
    description: "نخبة من أفضل الأكاديميين والخبراء في مجالاتهم.",
    icon: "Users",
  },
  {
    id: 3,
    title: "فرص عمل",
    description: "برامجنا مصممة لتلبية احتياجات سوق العمل الحديث.",
    icon: "Briefcase",
  },
  {
    id: 4,
    title: "برامج مميزة",
    description: "تطوير مستمر للمناهج لمواكبة أحدث التطورات العالمية.",
    icon: "Zap",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    name: "أحمد محمد",
    role: "خريج قسم تكنولوجيا التعليم",
    quote: "كانت تجربتي في الكلية نقطة تحول في حياتي المهنية، المهارات التي اكتسبتها جعلتني متميزاً في سوق العمل.",
    avatar: "https://avatar.iran.liara.run/public/boy?username=ahmed",
    gender: "male",
  },
  {
    id: 2,
    name: "سارة علي",
    role: "طالبة بقسم الإعلام التربوي",
    quote: "الكلية توفر بيئة إبداعية رائعة، والأساتذة دائماً ما يشجعوننا على الابتكار والتميز.",
    avatar: "https://avatar.iran.liara.run/public/girl?username=sara",
    gender: "female",
  },
  {
    id: 3,
    name: "محمود حسن",
    role: "خريج قسم التربية الفنية",
    quote: "وجدت في الكلية كل الدعم لتطوير موهبتي الفنية وتحويلها إلى مهنة احترافية.",
    avatar: "https://avatar.iran.liara.run/public/boy?username=mahmoud",
    gender: "male",
  },
];

export const VIDEOS: VideoCard[] = [
  {
    id: 1,
    title: "كلمة عميد الكلية للطلاب الجدد",
    role: "أ.د. عميد الكلية",
    thumbnail: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=1200",
    videoUrl: "#",
  },
  {
    id: 2,
    title: "جولة داخل معامل الكلية المتطورة",
    role: "فيديو تعريفي",
    thumbnail: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=800",
    videoUrl: "#",
  },
  {
    id: 3,
    title: "إنجازات الطلاب في المسابقات الدولية",
    role: "نشاط طلابي",
    thumbnail: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=800",
    videoUrl: "#",
  },
];
